/**
 * District to region mapping (for districts not yet in database)
 *
 * This is temporary glue logic until all districts are properly seeded in the database.
 * Once all districts have region assignments in the database, this mapping can be removed.
 *
 * Candidate for View Modes refactor: This mapping may need to be replaced with
 * database-driven region lookups when implementing region-scoped views.
 */
export const DISTRICT_REGION_MAP: Record<string, string> = {
  Alabama: "Southeast",
  Alaska: "Northwest",
  Appalachian: "Mid-Atlantic",
  Arizona: "West Coast",
  Arkansas: "South Central",
  Colorado: "Big Sky",
  Georgia: "Southeast",
  Hawaii: "West Coast",
  Illinois: "Great Lakes",
  Indiana: "Great Lakes",
  Iowa: "Great Plains South",
  Kansas: "Great Plains South",
  Kentucky: "Mid-Atlantic",
  Louisiana: "South Central",
  Michigan: "Great Lakes",
  Minnesota: "Great Plains North",
  Mississippi: "Southeast",
  Montana: "Big Sky",
  Nebraska: "Great Plains South",
  NewJersey: "Northeast",
  NewMexico: "Texico",
  NewYork: "Northeast",
  NorthCarolina: "Mid-Atlantic",
  NorthDakota: "Great Plains North",
  "NorthernCal-Nevada": "West Coast",
  NorthernNewEnglend: "Northeast",
  NorthernNewEngland: "Northeast",
  NorthIdaho: "Northwest",
  NorthernMissouri: "Great Plains South",
  NorthTexas: "Texico",
  Ohio: "Great Lakes",
  Oklahoma: "South Central",
  Oregon: "Northwest",
  PeninsularFlorida: "Southeast",
  "Penn-Del": "Northeast",
  Potomac: "Mid-Atlantic",
  SouthCarolina: "Southeast",
  SouthDakota: "Great Plains North",
  SouthernCalifornia: "West Coast",
  SouthernNewEngland: "Northeast",
  SouthIdaho: "Big Sky",
  SouthernMissouri: "Great Plains South",
  SouthTexas: "Texico",
  Tennessee: "Mid-Atlantic",
  Utah: "Big Sky",
  Washington: "Northwest",
  WestFlorida: "Southeast",
  WestTexas: "Texico",
  "Wisconsin-NorthMichigan": "Great Plains North",
  Wyoming: "Big Sky",
  Connecticut: "Northeast",
  Maine: "Northeast",
  Massachusetts: "Northeast",
  NewHampshire: "Northeast",
  Pennsylvania: "Northeast",
  Vermont: "Northeast",
  Virginia: "Mid-Atlantic",
  WestVirginia: "Mid-Atlantic",
  Florida: "Southeast",
  Nevada: "West Coast",
  NorthCalifornia: "West Coast",
  SouthCalifornia: "West Coast",
};
