ALTER TABLE `users` MODIFY COLUMN `role` ENUM(
  'STAFF',
  'CO_DIRECTOR',
  'CAMPUS_DIRECTOR',
  'CAMPUS_INTERN',
  'CAMPUS_VOLUNTEER',
  'DISTRICT_DIRECTOR',
  'DISTRICT_STAFF',
  'REGION_DIRECTOR',
  'REGIONAL_STAFF',
  'NATIONAL_STAFF',
  'NATIONAL_DIRECTOR',
  'FIELD_DIRECTOR',
  'CMC_GO_ADMIN',
  'ADMIN',
  'OTHER'
) NOT NULL;
